language: go
sudo: true
dist: trusty
notifications:
  email: false

env:
  - IMAGE_NAME=battle

stages:
  - test
  - name: deploy
    if: branch = master
  - name: promote
    if: branch = master

services:
  - docker

jobs:
  include:
    - stage: test
      go:
        - 1.10.x
        - 1.9.x
      addons:
        sonarcloud:
          organization: "jorgechato-github"
          token:
            secure: $SONAR_TOKEN
      before_script:
        - make install_dep
        - dep ensure
        - make install_unit
        - make install_dev
      script: make test
      after_script:
        - sonar-scanner

    - stage: deploy
      go: 1.10.x
      before_script:
        - make install_dep
        - dep ensure
      script:
        - make deploy
      after_script:
        - docker images
      before_deploy:
        - version="$(git describe --always --abbrev=0 --tags || echo '0.1')"
        - docker login -u "$QUAY_USER" -p "$QUAY_PASS" quay.io
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
      deploy:
        - provider: script
          script: docker push "quay.io/${QUAY_USER}/${IMAGE_NAME}:latest" && docker push "quay.io/${QUAY_USER}/${IMAGE_NAME}:${version}"
