language: go
sudo: true
dist: trusty
notifications:
  email: false

stages:
  - name: test
  - name: deploy
    if: branch = master OR tag =~ ^[0-9]+[.]{1}[0-9]+

jobs:
  include:
    - stage: test
      go:
        - 1.10.x
        - 1.9.x
      addons:
        sonarcloud:
          organization: "jorgechato-github"
          token:
            secure: $SONAR_TOKEN
      before_script:
        - make install_dep
        - dep ensure
        - make install_unit
        - make install_dev
      script: make test
      after_script:
        - sonar-scanner

    - stage: deploy
      go: 1.10.x
      env: IMAGE_NAME=battle
      services:
        - docker
      before_install:
        - make install_dep
        - dep ensure
      install:
        - make deploy
      after_install:
        - docker images
      before_script:
        - version="$(git describe --always --abbrev=0 --tags || echo '0.1')"
        - docker login -u "$QUAY_USER" -p "$QUAY_PASS" quay.io
        - docker tag "$IMAGE_NAME" "${QUAY_BASE}/${IMAGE_NAME}:latest"
        - docker tag "$IMAGE_NAME" "${QUAY_BASE}/${IMAGE_NAME}:${version}"
      script:
        - docker push "${QUAY_BASE}/${IMAGE_NAME}:latest"
        - docker push "${QUAY_BASE}/${IMAGE_NAME}:${version}"
