language: go
sudo: false
notifications:
  email: false

addons:
  sonarcloud:
    organization: "jorgechato-github"
    token:
      secure: $SONAR_TOKEN

stages:
  - test
  - name: deploy
    if: branch = master

before_script:

jobs:
  include:
    - stage: test
      go:
        - 1.10.x
        - 1.9.x
      go_import_path: github.com/jorgechato/battle-royale
      before_script:
        - make install_dep
        - dep ensure
        - make install_unit
        - make install_dev
      script:
        - make unit
        - make linter
        - make cov
      after_script:
        - sonar-scanner
    - stage: deploy
      go: 1.10.x
      go_import_path: github.com/jorgechato/battle-royale
      install: skip
      script: skip
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            repo: jorgechato/battle-royale
            branch: master
            tags: true
